### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by gregoranders** [brn/typescript-middleware#2]
Hope the trace helps. Local install, no packages installed globally.

```javascript
/node_modules/typescript-middleware/lib/option-parser.js:124
  if (!pathutil.exists(filePath)) {
                ^
TypeError: undefined is not a function
    at OptionParser._setLanguageAndTerritory (/node_modules/typescript-middleware/lib/option-parser.js:124:17)
    at OptionParser._setLocale (/node_modules/typescript-middleware/lib/option-parser.js:104:13)
    at OptionParser.parse (/node_modules/typescript-middleware/lib/option-parser.js:87:15)
    at module.exports (/node_modules/typescript-middleware/lib/middleware.js:171:16)
    at Object.<anonymous> (/gulpfile.js:29:31)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

node --version => v0.12.0
gulp --version => 3.8.11
tsc --version =>  1.4.1.0

**Comment by brn** [comment]
thanks for report.
I will confirm that.
